const salas = [
    {
        codigo: '001',
        tipo: 'Odontologia',
        preco: 'R$ 300',
        periodo: 'período 4h',
        descricao: 'Consultório Região Diferenciada em Santana - ZN',
        localizacao: 'Santana, São Paulo/SP',
        imagens: [
            '01.jpg',
            '02.jpg',
            '03.jpg',
            '04.jpg',
            '05.jpg',
            '06.jpg',
            '07.jpg',
            '08.jpg',
            '09.jpg',
            '10.jpg',
        ],
    },
    {
        codigo: '002',
        tipo: 'Odontologia',
        preco: 'R$ 120',
        periodo: 'hora',
        descricao: 'Consultório Odontológico - Av. Paulista (Sala 4)',
        localizacao: 'Bela Vista, São Paulo/SP',
        imagens: [
            '01.jpg',
            '02.jpg',
            '03.jpg',
            '04.jpg',
            '05.jpg',
            '06.jpg',
            '07.jpg',
            '08.jpg',
            '09.jpg',
            '10.jpg',
        ],
    },
    {
        codigo: '003',
        tipo: 'Medico',
        preco: 'R$ 300',
        periodo: 'período 4h',
        descricao: 'Consultório Médico ao Lado do Metrô Conceição!',
        localizacao: 'Vila Guarani (Z Sul), São Paulo/SP',
        imagens: [
            '01.jpg',
            '02.jpg',
            '03.jpg',
            '04.jpg',
            '05.jpg',
            '06.jpg',
            '07.jpg',
            '08.jpg',
            '09.jpg',
            '10.jpg',
        ],
    },
    {
        codigo: '004',
        tipo: 'Psicologia',
        preco: 'R$ 150',
        periodo: 'período 2h',
        descricao: 'Consultório de Psicologia - Jardins',
        localizacao: 'Jardins, São Paulo/SP',
        imagens: [
            '01.jpg',
            '02.jpg',
            '03.jpg',
            '04.jpg',
            '05.jpg',
            '06.jpg',
            '07.jpg',
            '08.jpg',
            '09.jpg',
            '10.jpg',
        ],  
    },
    {
        codigo: '005',
        tipo: 'Fisioterapia',
        preco: 'R$ 200',
        periodo: 'hora',
        descricao: 'Consultório de Fisioterapia - Vila Mariana',
        localizacao: 'Vila Mariana, São Paulo/SP',
        imagens: [
            '01.jpg',
            '02.jpg',
            '03.jpg',
            '04.jpg',
            '05.jpg',
            '06.jpg',
            '07.jpg',
            '08.jpg',
            '09.jpg',
            '10.jpg',
        ],
    },
    {
        codigo: '006',
        tipo: 'Fonoaudiologia',
        preco: 'R$ 180',
        periodo: 'período 3h',
        descricao: 'Consultório de Fonoaudiologia - Moema',
        localizacao: 'Moema, São Paulo/SP',
        imagens: [
            '01.jpg',
            '02.jpg',
            '03.jpg',
            '04.jpg',
            '05.jpg',
            '06.jpg',
            '07.jpg',
            '08.jpg',
            '09.jpg',
            '10.jpg',
        ],
    },
    {
        codigo: '007',
        tipo: 'Nutrição',
        preco: 'R$ 140',
        periodo: 'período 2h',
        descricao: 'Consultório de Nutrição - Pinheiros',
        localizacao: 'Pinheiros, São Paulo/SP',
        imagens: [
            '01.jpg',
            '02.jpg',
            '03.jpg',
            '04.jpg',
            '05.jpg',
            '06.jpg',
            '07.jpg',
            '08.jpg',
            '09.jpg',
            '10.jpg',
        ],
    },
    {
        codigo: '008',
        tipo: 'Odontologia',
        preco: 'R$ 250',
        periodo: 'período 3h',
        descricao: 'Consultório Odontológico - Tatuapé',
        localizacao: 'Tatuapé, São Paulo/SP',
        imagens: [
            '01.jpg',
            '02.jpg',
            '03.jpg',
            '04.jpg',
            '05.jpg',
            '06.jpg',
            '07.jpg',
            '08.jpg',
            '09.jpg',
            '10.jpg',
        ],
    },
    {
        codigo: '009',
        tipo: 'Medico',
        preco: 'R$ 280',
        periodo: 'período 4h',
        descricao: 'Consultório Médico - Morumbi',
        localizacao: 'Morumbi, São Paulo/SP',
        imagens: [
            '01.jpg',
            '02.jpg',
            '03.jpg',
            '04.jpg',
            '05.jpg',
            '06.jpg',
            '07.jpg',
            '08.jpg',
            '09.jpg',
            '10.jpg',
        ],
    },
    {
        codigo: '010',
        tipo: 'Psicologia',
        preco: 'R$ 130',
        periodo: 'período 2h',
        descricao: 'Consultório de Psicologia - Higienópolis',
        localizacao: 'Higienópolis, São Paulo/SP',
        imagens: [
            '01.jpg',
            '02.jpg',
            '03.jpg',
            '04.jpg',
            '05.jpg',
            '06.jpg',
            '07.jpg',
            '08.jpg',
            '09.jpg',
            '10.jpg',
        ],
    },
];

export default salas;
  